### ISSUE TITLE
not useable in Arduino IDE

### ISSUE THREAD

**Issue by p-h-a-i-l** [p-h-a-i-l/HoverboardAPI#1]
Arduino IDE can not handle submodules. Need to create release with flat structure and test..

**Comment by ahmed380** [comment]
> Arduino IDE can not handle submodules. Need to create release with flat structure and test..

Thanks Phail, I am struggling with integrating this in my arduino. I have nodeMCU which is based on ESP8266.  Let me know if I can help!

**Comment by p-h-a-i-l** [comment]
Very good, I need to push some cleanups through the protocol submodule and then I'll look into the API again. 
I will let you know when testing is needed ;)

**Comment by p-h-a-i-l** [comment]
Hello @ahmed380, compatibility to the Arduino IDE is working now. WOuld be great if you'd test!
Have a look at https://github.com/bipropellant/bipropellant-hoverboard-api (This repo is moved there)
